smucclaw/l4-ide

jl4/experiments/order-invariance.l4
=> added experiment to illustrate issue: forward references currently invalid; requesting order invariance

jl4/experiments/term-expansion.l4
=> experiment to illustrate request for term expansion

package-lock.json, ts-apps/jl4-web/package.json, ts-apps/jl4-web/src/routes/+page.svelte, ts-shared/viz-expr/viz-expr.ts
```
❯ corepack npm run check
> jl4-web@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./tsconfig.json
====================================
Loading svelte-check in workspace: /Users/ymh/_git/smucclaw/tmp-debug/fix-css/l4-ide/ts-apps/jl4-web
Getting Svelte diagnostics...
====================================
svelte-check found 0 errors and 0 warnings
```
npm run dev:
=> jl4-web: Fix Effect-related type error (was due to conflicting dependency versions)

jl4/GRAMMAR.md, jl4/examples/not-ok/tests/parse-error4.ep.golden, jl4/examples/not-ok/tests/parse-error4.golden, jl4/examples/ok/aka.l4, jl4/examples/ok/tests/aka.ep.golden, jl4/examples/ok/tests/aka.golden, jl4/lsp/LSP/L4/Handlers.hs, jl4/lsp/LSP/L4/SemanticTokens.hs, jl4/lsp/LSP/L4/Viz/Ladder.hs, jl4/src/L4/Evaluate.hs, jl4/src/L4/Lexer.hs, jl4/src/L4/Parser.hs, jl4/src/L4/Parser/ResolveAnnotation.hs, jl4/src/L4/Print.hs, jl4/src/L4/Syntax.hs, jl4/src/L4/TypeCheck.hs
=> Implement AKA

jl4/jl4.cabal, jl4/lsp/LSP/L4/Handlers.hs, jl4/lsp/LSP/L4/Rules.hs, jl4/src/L4/FindDefinition.hs, jl4/src/L4/HoverInfo.hs, jl4/src/L4/Lexer.hs, jl4/src/L4/Main.hs, jl4/src/L4/Parser/SrcSpan.hs, jl4/src/L4/Syntax.hs, jl4/src/L4/TypeCheck.hs, jl4/src/L4/TypeCheck/Environment.hs, jl4/src/L4/TypeCheck/Types.hs, jl4/src/L4/TypeCheck/With.hs
=> Split the type checker into several modules

jl4/examples/ok/citations.csv, jl4/examples/ok/ref.l4, jl4/examples/ok/tests/ref.ep.golden, jl4/jl4.cabal, jl4/src/L4/Citations.hs
=> [feat] match against regexes for reference annotations

jl4/examples/ok/ref.l4, jl4/examples/ok/tests/ref.ep.golden, jl4/jl4.cabal, jl4/lsp/LSP/L4/Handlers.hs, jl4/lsp/LSP/L4/Rules.hs, jl4/src/L4/Citations.hs, jl4/src/L4/Lexer.hs, jl4/src/L4/Parser.hs
resolves #197 
- add the ref-map token to the parser
- try to add ref-map to the intervalmap
=> implement ref-map

ts-apps/jl4-web/src/error.html, ts-apps/jl4-web/src/lib/utils.ts, ts-apps/jl4-web/src/routes/+layout.ts, ts-apps/jl4-web/src/routes/+page.svelte, ts-apps/jl4-web/svelte.config.js
Depends on #223  -- i.e., please review that first.
=> Refactor: Remove unnecessary use of state rune for `persistSession` in jl4-web

ts-apps/jl4-web/src/routes/+page.svelte
=> Experiment with a wider divider between editor and viz panes

jl4-decision-service/README.md, jl4-decision-service/jl4-decision-service.cabal, jl4-decision-service/src/Application.hs, jl4-decision-service/src/Backend/Jl4.hs, jl4-decision-service/src/Examples.hs, jl4-decision-service/src/Options.hs, jl4-decision-service/src/Schema.hs, jl4-decision-service/src/Server.hs
Extracted from #241 
TODO:
> Tests currently fail, probably because you changed the API of the decision service without adapting the tests?
=> decision service tweaks: support --sourcePaths to load yaml from disk; finesse `Inputs` management; add support for CORS.

jl4-lsp/app/Server.hs, jl4/libraries/prelude.l4, jl4/libraries/tests/prelude.ep.golden, jl4/libraries/tests/prelude.golden, jl4/tests/Main.hs, nix/jl4-lsp/configuration.nix
Resolves #268 
- make `IMPORT`s work with the webdemo
- add new directory to put libraries into and add it to the tests that should be ok. 
- goto definition does not work yet. I will try to figure out if it's feasible
Example:
https://jl4.well-typed.com/?id=5896859e-a56c-4b77-a9ba-aa7db4c3c0a1
=> makes IMPORTs work with the webdemo

jl4-core/src/L4/FindDefinition.hs, jl4-core/src/L4/Lexer.hs, jl4-core/src/L4/Parser.hs, jl4-core/src/L4/Syntax.hs, jl4-lsp/app/LSP/L4/Handlers.hs, jl4-lsp/src/LSP/L4/Actions.hs, jl4-lsp/src/LSP/L4/Rules.hs, jl4/tests/Main.hs
=> IMPORT statement refinements

jl4-core/src/L4/TypeCheck.hs, jl4/examples/ok/reverse.l4, jl4/examples/ok/reverseaux.l4, jl4/examples/ok/tests/reverse.ep.golden, jl4/examples/ok/tests/reverse.golden, jl4/examples/ok/tests/reverseaux.ep.golden, jl4/examples/ok/tests/reverseaux.golden
=> Fix type checker

jl4-core/src/L4/Lexer.hs, jl4-core/src/L4/Parser.hs, jl4-lsp/src/LSP/L4/Actions.hs
- basic completions for directives and annotations
- display a type function instead of arity n
=> fix minor issues

jl4-core/src/L4/Parser.hs, jl4/examples/ok/nested-patterns.l4, jl4/examples/ok/tests/nested-patterns.ep.golden, jl4/examples/ok/tests/nested-patterns.golden
=> Allow parentheses in patterns.

ts-apps/decision-logic-visualizer/src/lib/algebraic-graphs/dag.ts, ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte, ts-apps/decision-logic-visualizer/src/lib/displayers/flow/paths-list.svelte, ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-lir.svelte.ts, ts-apps/decision-logic-visualizer/src/style.css, ts-apps/jl4-web/src/routes/+page.svelte, ts-apps/webview/src/app.css
This reverts commit 6e4872267fdb1a27fa53158c54f09dfd10f89622.
I panicked when I saw that CI was broken, but upon looking more closely, it cannot be because of these changes.
In particular, if we do `git diff c14607bce30f140f6c6b9513dee918d6703c9c83 7212c94`, we'll see that there hasn't been any change to anything that could affect the haskell CI. And `cabal build all` works on my machine.
=> Reapply "Merge pull request #300 from smucclaw/ym-han/improve-paths-css"

jl4-core/src/L4/TypeCheck.hs, jl4-lsp/src/LSP/L4/Actions.hs
=> Fixing some bugs

jl4-core/src/L4/Lexer.hs, jl4/examples/ok/comments.3.l4, jl4/examples/ok/tests/comments.3.ep.golden, jl4/examples/ok/tests/comments.3.golden
=> Allow C-style comments.

ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-lir.svelte.ts
We can wait till Thurs EST / Jersey time to merge this in.
=> Viz: Quick clean up + add quick doc / comment

jl4-core/src/L4/Annotation.hs, jl4-core/src/L4/Parser.hs, jl4-core/src/L4/Parser/ResolveAnnotation.hs, jl4-core/src/L4/Parser/SrcSpan.hs, jl4-core/src/L4/Print.hs, jl4-core/src/L4/Syntax.hs, jl4-core/src/L4/TypeCheck.hs, jl4-lsp/src/LSP/L4/Rules.hs, jl4-lsp/src/LSP/L4/SemanticTokens.hs
When going to a definition of an import, you're now brought to the module that is being imported.
=> Implement goto definition for imports

jl4-core/src/L4/Print.hs, jl4-core/src/L4/TypeCheck.hs, jl4-core/src/L4/TypeCheck/Types.hs, jl4/examples/ok/nested-sections.l4, jl4/examples/ok/tests/nested-sections.ep.golden, jl4/examples/ok/tests/nested-sections.golden, jl4/examples/ok/tests/nested-sections.nlg.golden
=> [fix] make nested sections work with AKAs

jl4-core/libraries/prelude.l4, jl4-core/libraries/tests/prelude.ep.golden
=> [fix] any should have FALSE, not TRUE as the identity for OR

ts-apps/decision-logic-visualizer/src/lib/displayers/paths-list.svelte, ts-apps/decision-logic-visualizer/src/lib/layout-ir/paths-list.ts
Depends on #375   -- please review that first
=> Viz: Refactor -- Improve `highlightPaths`'s signature

doc/dev/frontend-dev.md, ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow.svelte, ts-apps/vscode/src/extension.mts, ts-shared/jl4-client-rpc/README.md
* Viz: Add quick runtime check for whether a Lir-related precondition is satisfied
* extension.mts: Make logged messages more human-readable and informative to facilitate future debugging
* Doc: Add some developer-oriented docs on the frontend codebase
=> Frontend infra, doc: Misc refactor / infra improvements. And add some developer-oriented docs on the frontend codebase

jl4-lsp/src/LSP/L4/Rules.hs
=> [fix] used the wrong monoid for Maybe when figuring out file path

flake.lock
=> [feat] update the nixpkgs version to get new haskellPackages set

ts-apps/jl4-web/src/routes/+page.svelte
=> [fix] don't get stuck on empty uri

jl4-core/src/L4/Evaluate/ValueLazy.hs, jl4-core/src/L4/EvaluateLazy.hs, jl4-core/src/L4/EvaluateLazy/ContractFrame.hs, jl4-core/src/L4/EvaluateLazy/Machine.hs, jl4-core/src/L4/Lexer.hs, jl4-core/src/L4/Nlg.hs, jl4-core/src/L4/Parser.hs, jl4-core/src/L4/Parser/ResolveAnnotation.hs, jl4-core/src/L4/Print.hs, jl4-core/src/L4/Syntax.hs, jl4-core/src/L4/TypeCheck.hs, jl4-core/src/L4/TypeCheck/Annotation.hs, jl4-core/src/L4/TypeCheck/Environment.hs, jl4-core/src/L4/TypeCheck/Types.hs, jl4-lsp/src/LSP/L4/SemanticTokens.hs, jl4/examples/ok/contracts.l4, jl4/examples/ok/tests/contracts.ep.golden, jl4/examples/ok/tests/contracts.golden, jl4/examples/ok/tests/contracts.nlg.golden
- actions are now patterns that are matched on when checking if the action matches
- the pattern may bind variables that can be used in a PROVIDED clause that evaluates to a boolean - if the boolean is True, the action matches, otherwise it doesn't
- fixes #457 
- fixes #439 
- fixes #455 
- fixes #483 
- fixes #408
- fixes #488
=> [feat] make action a pattern and add PROVIDED

jl4-core/src/L4/EvaluateLazy/Machine.hs, jl4-core/src/L4/TypeCheck/Environment.hs, jl4/examples/ok/contracts.l4, jl4/examples/ok/tests/contracts.ep.golden, jl4/examples/ok/tests/contracts.golden, jl4/examples/ok/tests/contracts.nlg.golden
=> [feat] implement ADVANCETIMETO construct

ts-apps/vscode/language-configuration.json, ts-apps/vscode/package.json
=> Enabled quality of life VSCode settings

jl4-core/src/L4/EvaluateLazy/Machine.hs, jl4/examples/ok/tests/elem.golden
- report the values that were tried for comparison in runBinOpEquals
- report when user tried to comparse ASSUMED values
=> [feat] improve error messages

jl4-core/src/L4/TypeCheck.hs, jl4-core/src/L4/TypeCheck/Types.hs, jl4-lsp/app/LSP/L4/Handlers.hs, jl4-lsp/src/LSP/L4/Actions.hs, jl4-lsp/src/LSP/L4/Rules.hs
This adds scoped completion items based on environments at some specific source location
=> add scoped completion items

ts-shared/l4-ladder-visualizer/src/lib/data/viz-expr-to-lir.ts, ts-shared/l4-ladder-visualizer/src/lib/displayers/paths-list.svelte, ts-shared/l4-ladder-visualizer/src/lib/layout-ir/ladder-graph/ladder-dag-helpers.ts, ts-shared/l4-ladder-visualizer/src/lib/layout-ir/ladder-graph/ladder.svelte.ts, ts-shared/l4-ladder-visualizer/src/lib/layout-ir/node-paths-selection.ts
=> Viz: Fix path pretty printing bug (path graphs had to be (re-?)augmented with edge labels)

jl4-core/src/L4/Citations.hs, jl4-core/src/L4/Lexer.hs, jl4-core/src/L4/Parser.hs, jl4-core/src/L4/TypeCheck/Environment/TH.hs, jl4-lsp/src/LSP/L4/Actions.hs, jl4/examples/lsp/semantic-tokens/tests/annotations.golden
#571 should be closed first
Closes #572
=> Lexer refactoring

README.md, doc/10-data-types.md, doc/20-basic-syntax.md, doc/25-functions.md, jl4-decision-service/README.md, nix/README.md
=> Fix link in additional resources of jl4-decision-service

Dev.md, jl4-core/src/L4/Lexer.hs, jl4-core/src/L4/Parser.hs, jl4/examples/ok/contracts.l4, jl4/examples/ok/tests/contracts.ep.golden, ts-apps/jl4-web/scripts/copy-examples.ts, ts-apps/jl4-web/src/lib/components/example-selector.svelte, ts-apps/jl4-web/src/routes/+page.svelte
- allow may and do in place of must (closes #591) 
- add empty document to examples (closes #600)
- push the URL to the history after sharing (closes #597)
- explain how the services play together (closes #589)
=> a collection of small changes

LICENSE
as previously stipulated by terms of grant, and agreed with CCLAW management in 2020
=> standardize license file

jl4/app/Main.hs, jl4/jl4.cabal
=> add `jl4-cli -a` flag to print the parsed AST
