smucclaw/l4-ide

jl4/lsp/LSP/L4/Rules.hs
jl4/lsp/LSP/L4/SemanticTokens.hs

Removes the attempt to colourize functions (e.g., AppForm with non-empty parameters) and fixes a hole traversal.

Fix Anno traversal for semantic syntax highlighting

---

ts-apps/jl4-web/src/error.html
ts-apps/jl4-web/svelte.config.js

Turns out that to produce the index.html (when set to no-ssr), I have to set `fallback` in sveltekit config to `index.html` and remove the previous fallback html page. The SvelteKit docs weren't super clear on this.
(btw I might be doing something wrong git-wise; let me know if so!)

Fix deployment issue with PR #226

---

ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte

Depends on #239  --- please review that first.
This addresses #176  to some extent: the jarring fitting to view process is no longer visible.
There is, however, a flicker on update. This is because we re-render the component and re-layout the nodes every time we do a visualization update, and the nodes are hidden while they're being layouted. Improving this is out of the scope of this PR.
The VSCode webview could also benefit from a debounce, but that can be done in a future pr.

Viz: Improve how it looks on update by only displaying the ladder flow graph after it's been fit to view

---

jl4/examples/ok/tests/typesynonms.ep.golden
jl4/examples/ok/tests/typesynonms.golden
jl4/examples/ok/typesynonms.l4
jl4/src/L4/TypeCheck.hs

Fixes #233.
The problem was that type synonym expansion is being done in unify, but for the purposes of generating error messages, we check function applications using a specialised function, in which we did not perform type synonym expansion.

Improve type synonym expansion.

---

ts-apps/decision-logic-visualizer/src/lib/algebraic-graphs/adjacency-map-directed-graph.ts
ts-apps/decision-logic-visualizer/src/lib/data/viz-expr-to-lir.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/ladder-lir-to-sf.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/layout.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-edges/ladder-edge.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/bundling-sink.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/bundling-source.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/svelteflow-types.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/core.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-lir.svelte.ts
ts-apps/decision-logic-visualizer/src/style.css
ts-apps/decision-logic-visualizer/static/style/themes/default.css

Depends on #245  -- please review that first.
This PR adds explanatory labels / annotations for the nodes and edges; whether these labels should be displayed can be toggled by the user.
The edge labels can also be used when pretty printing the linearized paths; that will be done in a different PR.
And in the future, we could display NLG annotations as node or edge labels too.
I considered trying to put the zen button above the fit view button, but I wasn't able to see a way to do that within 1 min.
With NOT:

Viz: Add explanatory labels / annotations for edges and vertices

---

package-lock.json
ts-apps/decision-logic-visualizer/package.json
ts-apps/decision-logic-visualizer/src/lib/algebraic-graphs/base-adjacency-map.ts
ts-apps/decision-logic-visualizer/src/lib/algebraic-graphs/dag.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/paths-list.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/svelteflow-types.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-lir.svelte.ts
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/toggle-group/index.ts
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/toggle-group/toggle-group-item.svelte
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/toggle-group/toggle-group.svelte
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/toggle/index.ts
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/toggle/toggle.svelte
ts-apps/decision-logic-visualizer/src/lib/utils.ts
ts-apps/decision-logic-visualizer/src/style.css
ts-apps/decision-logic-visualizer/src/tests/alga-dag.test.ts
ts-apps/decision-logic-visualizer/src/tests/number-wrapper.ts
ts-apps/jl4-web/src/style.css

I'll implement 'use edge labels when pretty printing the linearized paths' in another PR.
I ended up just leaving the alga stuff in here, even though it's not related to pathslist, because the PR isn't too big (the shadcn svelte stuff is a copy-paste) and the commits weren't the cleanest / easiest to move

Viz: Enable highlighting / unhighlighting *multiple* lin paths. And other misc PathsList and algebraic-graphs improvements.

---

ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/bool-var.svelte

The background of the bool var node was such that it was obscuring the border at the corners. This PR fixes that.

Viz: Fix issue from prev PR with background of the bool var node obscuring the border

---

ts-apps/jl4-web/src/routes/+page.svelte

I was going to say it would be better if we had more informative or explicit response types from the language server. (My a priori thought was: Checking for whether the response is null and doing nothing if it's null seems fragile, or at least, makes it hard to tell if that should indeed be the desired behavior.)
But then I saw that the LSP spec actually seems to mandate this?
> The result property of the ResponseMessage should be set to null in this case to signal a successful request.
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#:~:text=If%20a%20request%20doesn't,to%20signal%20a%20successful%20request.

Quick fix: Modify jl4-web middleware handler to not show error message when it shouldn't, following the strategy taken in the vscode extn

---

.github/workflows/build.yml
package-lock.json
ts-apps/decision-logic-visualizer/package.json

The check seems to fail, as desired, in at least one case when package.json is not in sync with the lockfile:
https://github.com/smucclaw/l4-ide/actions/runs/14133585682/job/39599821973?pr=305

TS CI: Check if the package.json is in sync with lockfile. (And remove a dependency from ladder/dlv package.)

---

ts-apps/decision-logic-visualizer/src/lib/algebraic-graphs/dag.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/paths-list.svelte
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-lir.svelte.ts
ts-apps/decision-logic-visualizer/src/style.css
ts-apps/jl4-web/src/routes/+page.svelte
ts-apps/webview/src/app.css

Fix edge case bug in edge label. Fix CSS variable name. Improve paths-related usability-related CSS and pretty printing. Improve JL4-webview CSS.

---

ts-apps/jl4-web/src/routes/+page.svelte

I can't actually perceive the differences in colors very well, so I'm not 100% sure that it is consistent. But here's a first attempt at trying to make the monaco theme more in line with the ladder diagram's `--primary` color (which is what gets used for the node border color etc).

Make monaco editor theme foreground colors the same as ladder's `--primary` (modulo rounding error)

---

ts-apps/decision-logic-visualizer/src/lib/data/viz-expr-to-lir.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/svelteflow-types.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-lir.svelte.ts

Closes #311 
but when it *is* an NNF:
Haven't tested this super extensively tho

Viz: Only display 'List Paths' button if the ladder graph is a NNF

---

jl4-core/src/L4/HoverInfo.hs
jl4-core/src/L4/Nlg.hs
jl4-core/src/L4/Parser.hs
jl4-core/src/L4/Syntax.hs
jl4-core/src/L4/TypeCheck.hs
jl4-core/src/L4/TypeCheck/Annotation.hs
jl4-core/src/L4/TypeCheck/Types.hs
jl4-lsp/src/LSP/L4/Actions.hs
jl4/examples/ok/tests/nlg_lin2.nlg.golden

We expose the NLG linearisation to the `InfoTree`. This makes it easy to discover and can be used as a form of documentation.
Additionally, add a bunch of type and name resolution to the AST after type checking.
Similarly to the NLG annotations, we need to be careful to add the additional type information when the respective type information is actually available.
For example, when new variables are brought into scope, for example in:
```
...
CONSIDER x
WHEN y FOLLOWED BY ys THEN y
OTHERWISE 0
```
then the `Resolved` `y` is only in scope within the `inferBranch` code, i.e. `THEN y` part. Thus, we need to make sure to add type information to `y` after we have typechecked the body of branch.
The same logic is applied to anything that brings a new binder into scope.
As a rule of thumb, …

Expose NLG information in Hover text

---

jl4-core/src/L4/Parser.hs
jl4/examples/ok/operators-issue336-1.l4
jl4/examples/ok/operators-issue336-2.l4
jl4/examples/ok/operators.l4
jl4/examples/ok/tests/operators-issue336-1.ep.golden
jl4/examples/ok/tests/operators-issue336-1.golden
jl4/examples/ok/tests/operators-issue336-1.nlg.golden
jl4/examples/ok/tests/operators-issue336-2.ep.golden
jl4/examples/ok/tests/operators-issue336-2.golden
jl4/examples/ok/tests/operators-issue336-2.nlg.golden
jl4/examples/ok/tests/operators.ep.golden
jl4/examples/ok/tests/operators.golden
jl4/examples/ok/tests/operators.nlg.golden

Fixes #336.
There's a small price to pay that parsing across lines with parentheses remains weird, and is now weird in a slightly different way. But as this was a weird case before, I don't care too much.

Improve same-line parsing logic.

---

ts-apps/decision-logic-visualizer/src/lib/eval/eval.ts

This adapts and generalizes a suggestion of @fendor 's.
(I've also continued doing a bit more on this front, e.g. removing the `Value` type from `eval/type.ts` and cleaning up related things a bit in a subsequent PR, on the `ym-han/issue-292` branch.)

Viz: Make it clearer in the types that the frontend evaluator only works with UBooleans

---

jl4-lsp/src/LSP/L4/Viz/Ladder.hs
jl4-lsp/src/LSP/L4/Viz/VizExpr.hs
ts-apps/decision-logic-visualizer/src/lib/data/viz-expr-to-lir.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-props.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-graph/ladder.svelte.ts
ts-apps/decision-logic-visualizer/src/routes/+page.svelte
ts-apps/jl4-web/src/routes/+page.svelte
ts-apps/webview/src/routes/+page.svelte
ts-shared/viz-expr/viz-expr.ts

This PR removes IRDecl, and thereby simplifies the code in the Ladder backend (as well as in the downstream consumers).
Viz still seems to show up.

Viz: Refactor --  Inline FunDecl / Remove IRDecl, since we probably won't be Ladder-visualizing other sorts of Decls

---

ts-apps/vscode/src/extension.mts

Quick refactor (the point of this will become clearer when I add more requests...)
The refactor doesn't seem to have broken stuff

Refactor extension.mts: Clean up the webview messenger initialization code

---

ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/app.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/ladder-env-provider.svelte
ts-apps/decision-logic-visualizer/src/lib/ladder-env.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/core.ts

Depends on #393  -- please review that first
This should be a fairly straightforward refactor. I'll make sure to run it by Jimmy, so no need to worry too much about the Typescript stuff.

Viz: Refactor LadderEnv, to prepare for threading `L4Connection` into the visualizer. Add a LadderEnvProvider component

---

ts-apps/decision-logic-visualizer/src/lib/l4-connection.ts
ts-shared/jl4-client-rpc/custom-protocol.ts
ts-shared/viz-expr/eval-on-backend.ts

Depends on #398 
Quick refactoring:
- Refactor: Use the `makeL4RpcRequestType` smart ctor for making EvalAppRequestType (forgot to do this before). 
- Jimmy pointed this out too.
- Refactor: Make section heading more precise
- Refactor: Simplify EvalAppRequestParams: remove the $type tag

Client-side RPC refactor for readability

---

jl4-lsp/src/LSP/L4/Viz/VizExpr.hs
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/app.svelte
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-graph/ladder.svelte.ts
ts-apps/jl4-web/src/routes/+page.svelte
ts-apps/webview/src/routes/+page.svelte
ts-shared/viz-expr/viz-expr.ts

* Standardize on `verDocId` fieldname
* TS infra: Improve logging of user's bindings / assignment when calling frontend eval's
* Viz: Add some async/awaits that I had missed

Quick ladder fixes

---

jl4-lsp/app/LSP/L4/Handlers.hs
jl4-lsp/jl4-lsp.cabal
jl4-lsp/src/LSP/L4/Viz/CustomProtocol.hs

Changes:
* Fix typo from a previous pr
* Init `LSP.L4.Viz.CustomProtocol` with `EvalAppMethodName` and backend version of the payloads for `l4/evalApp`
* Handlers.hs: Stub out draft / dummy handler for `l4/evalApp`; just return null for now
The following screenshot demonstrates how the server will handle the request and respond with Null when we click on `arg1`.
* Note, again, that you'll need to set dev mode to true to see this.
* Don't worry about UI for arg1 --- the UI won't update till we actually send a False or True or Unknown result back.

Ladder backend: Stub out a draft / dummy handler for the custom request `l4/evalApp` that parses request params but just returns Null for now (#376)

---

jl4-core/jl4-core.cabal
jl4-core/src/L4/EvaluateLazy.hs
jl4-core/src/L4/EvaluateLazy/Machine.hs

- introduce a new monad `Machine` that only contains the instructions of the machine 
- interpret  this Monad into `Eval` to run the machine 
- make each of the forward and backwards Machine instruction sequences return a `Config` that can the be use to interpret the respecting functions with, to make the mutual recursion explicit.

refactor the evaluator to use an explicit monad and configurations for mutual recursion

---

jl4-core/jl4-core.cabal
jl4-core/src/L4/Evaluate.hs
jl4-core/src/L4/Evaluate/Operators.hs
jl4-core/src/L4/Evaluate/Value.hs
jl4-core/src/L4/Evaluate/ValueLazy.hs
jl4-core/src/L4/EvaluateLazy.hs
jl4-core/src/L4/EvaluateLazy/Machine.hs
jl4-core/src/L4/Lexer.hs
jl4-core/src/L4/Nlg.hs
jl4-core/src/L4/Parser.hs
jl4-core/src/L4/Print.hs
jl4-core/src/L4/Syntax.hs
jl4-core/src/L4/TypeCheck/Environment.hs
jl4-core/src/L4/Utils/Ratio.hs
jl4-decision-service/src/Backend/Jl4.hs
jl4/examples/ok/fib.l4
jl4/examples/ok/float.l4
jl4/examples/ok/tests/fib.ep.golden
jl4/examples/ok/tests/fib.golden
jl4/examples/ok/tests/float.ep.golden
jl4/examples/ok/tests/float.golden
jl4/examples/ok/tests/float.nlg.golden

We change the 'NUMBER' type to work with rational numbers instead of only integers.
This allows us to use floating point literals, such as `2.0`, and `2.3`, and we still support integer literals, e.g. `1`, `2`.
Since 'NUMBER' is now backed by `Rational`, we cannot represent irrational numbers accurately, but at least to some approximation. The advantage of `Rational` over `Double` is that we do not suffer from IEEE decisions, such as `1.0 / 0.0 = NaN` (or `NaN` in general) and the usual floating point inaccuracies such as `0.1 + 0.2 = 0.3` is indeed `TRUE` in L4.
We introduce the following functions for working with 'NUMBER'
* '`IS INTEGER'`: returns 'TRUE' iff the number is an integer
* 'ROUND': rounds to the closest whole integer
* 'FLOOR': truncates to the next smallest integer
* …

Implement floating point literals

---

jl4-core/src/Base.hs
jl4-core/src/L4/EvaluateLazy.hs
jl4-core/src/L4/EvaluateLazy/Machine.hs
jl4-core/src/L4/Syntax.hs
jl4-lsp/app/LSP/L4/Handlers.hs
jl4-lsp/src/LSP/Core/Shake.hs
jl4-lsp/src/LSP/L4/Actions.hs
jl4-lsp/src/LSP/L4/Rules.hs
jl4-lsp/src/LSP/L4/Viz/CustomProtocol.hs
jl4-lsp/src/LSP/L4/Viz/Ladder.hs
jl4-lsp/src/LSP/L4/Viz/VizExpr.hs
jl4/tests/Main.hs
ts-apps/decision-logic-visualizer/src/lib/eval/eval.ts

* eval app handler: Return LSPErrorCodes_ContentModified if server's version does not match version in eval app request from client
* Flesh out the eval app handler on the backend.
* Prep an 'app expr maker' when the Decide is first visualized, to be used when the client sends an eval App request.
* When handling the request, we basically extend the module with an eval directive and return the result of that
* Augment the eval directive with whatever local decls are in scope, to handle the sort of local decl examples below
* Add and expose `execEvalExprInContextOfModule` from EvaluateLazy. This is in the vein of what @kosmikus recommended, except that I filter out any existing directives instead of making a module with an import (because making the import requires a Resolved)
* Add a …

Ladder backend: Finish implementing the eval app handler

---

jl4-lsp/src/LSP/L4/Viz/Ladder.hs

Closes #419 
* Remove obsoleted VizError variant
* Throw InvalidDecideMustHaveBoolRetType error if the Decide under consideration does not return a boolean

Viz: Don't show Viz codelens (by throwing error) if Decide does not return a boolean (#419)

---

jl4-lsp/app/LSP/L4/Handlers.hs
jl4-lsp/src/LSP/L4/Viz/CustomProtocol.hs

Depends on #440 
VizHandler refactor
* Add VizHandler monad and helpers, and IsLadderRequestParams typeclass
* Handlers.hs: Refactor the eval app handler to use VizHandler
Params, payloads types for inlining exprs (+ some clean up of eval app tojson)
* CustomProtocol.hs: Fix EvalAppResult's ToJSon encoding
* CustomProtocol.hs: Add custom method type for inlining exprs
* Stub out the InliningExprs handler in the VizHandler monad
Will implement the logic for whether this or that subexpr's `canInline` is true/false in the next PR, along with the handler for inlining exprs

Ladder backend: Add a prelim VizHandler monad, and refactor eval app handler to use that. Stub out the inlineExprs handler

---

jl4-core/src/L4/Lexer.hs
jl4-core/src/L4/Parser.hs
jl4/examples/ok/record.l4
jl4/examples/ok/tests/record.ep.golden

In particular, in the following cases:
* Function Arguments
* Type Arguments
* Record field definitions
Articles are valid with `:`, e.g.
```
GIVEN a: A BOOLEAN
foo a MEANS a AND a
```
The token ":" is always hidden and will not be displayed in error messages to the user.
Closes #461

Implement ":" as a synonym for "IS"

---

jl4/app/Main.hs

not sure if this is the correct way to deal with multiple recorders, but it works.
upon success, exits 0
upon failure, exits nonzero
upon success, also refrains from printing the reformatted input to output, unless called with `-v`

jl4-cli: distinguish success vs failure runs via exitcode

---

ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/ubool-var.svelte
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/tooltip/index.ts
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/tooltip/tooltip-content.svelte
ts-apps/decision-logic-visualizer/src/lib/ui-primitives/tooltip/tooltip-trigger.svelte

I've decided to go with the '+' symbol for node expansion. Unlike directional indicators (e.g., arrows pointing up/down/left/right), '+' conveys a non-directional, spatially neutral action that aligns better with how expansion works in our graph: the layout adjusts globally rather than unfolding in-place along a fixed axis. 
Using a neutral symbol avoids misleading spatial cues and keeps the interaction consistent with common UI expectations around “revealing more.” 
Alternative symbols (e.g., arrows or ellipses) were considered but seem less intuitive for this context, as they typically imply directional growth or continuation rather than full structural unfolding.

Inlining expr UI

---

ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/app.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/ubool-var.svelte
ts-apps/decision-logic-visualizer/src/lib/eval/assignment.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-graph/ladder.svelte.ts

* Refactor: Simplify the updating of value in the AppLirNode displayer and UBoolVarLirNode displayer, by leveraging how SF nodes' `data` seems reactive
* Refactor: Remove redundant state related to uboolvarnodes' values (and redundant logic synchronizing such state)

Viz: Refactor: Simplify / improve some handling and updating of values

---

ts-apps/decision-logic-visualizer/src/lib/displayers/flow/helpers/with-selectable-node-context-menu.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/app.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/ubool-var.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/paths-list.svelte
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-graph/ladder.svelte.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/paths-list.ts

Have displayers trigger and check for node selection by interacting with LadderGraphLirNode, instead of the NodeSelectionTracker. This obviates the need to duplicate state about whether the node is selected in the node displayer

Viz: Refactor: Have displayers trigger and check for node selection by interacting with LadderGraphLirNode, instead of the NodeSelectionTracker

---

ts-apps/decision-logic-visualizer/src/lib/data/viz-expr-to-lir.ts
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/flow-base.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/helpers/with-non-bundling-node-base-styles.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/helpers/with-selectable-node-context-menu.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/app.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/false-expr.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/not-end.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/not-start.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/true-expr.svelte
ts-apps/decision-logic-visualizer/src/lib/displayers/flow/sf-custom-nodes/ubool-var.svelte
ts-apps/decision-logic-visualizer/src/lib/ladder-env.ts
ts-apps/decision-logic-visualizer/src/lib/layout-ir/ladder-graph/ladder.svelte.ts
ts-apps/decision-logic-visualizer/src/style.css

* Make it possible to select / highlight the whole NOT subgraph by selecting the NotStart node
* Re-layout when node selection changes, so that paths won't end up looking visually mis-aligned.
---------
* Refactor: Make it easier to change the amount by which path width changes on highlight
* Refactor: Rename with-contentful-node-styles to with-non-bundling-node-base-styles
* Make it impossible for non-Ladder-Graph consumers to use the node selection tracker object without going through LadderGraphLirNode

Viz: Make it possible to select / highlight the whole NOT subgraph by selecting the NotStart node. And misc refactoring / cleaning up

---

jl4-decision-service/src/Backend/Api.hs
jl4-decision-service/src/Backend/Jl4.hs

Perform type-directed deserialisation of nested objects and arrays.
Closes #326 and #329

Allow nested arguments for the L4 backend in jl4-decision-service
